apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  name: mysql-vm
  namespace: ecom-8b6tg
  labels:
    vm-selector: mysql-vm-lb-azvo
    mysql-lb: vm-lb-selector
    topology.kubernetes.io/zone: zone1
spec:
  className: best-effort-small
  # Friendly image name: ubuntu-24.04
  imageName: vmi-0fc4c067a6f24a195
  storageClass: vsan-default-storage-policy
  powerState: PoweredOn
  bootstrap:
    cloudInit:
      rawCloudConfig:
        name: mysql-vm-bootstrap-secret
        key: user-data
